Factory/Models/Machine.cs
using System.Collections.Generic;


namespace Factory.Models
{
    public class Machine
    {
        public int MachineId { get; set; }   
        public int EngineerId { get; set; }
        public string MachineName { get; set; }
        public string ManufactureDate { get; set; }
        public List<EngineerMachine> JoinEntities { get; }

    }
}

Factory/Controllers/EngineersController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
    public class EngineersController : Controller
    {
        private readonly FactoryContext _db;

        public EngineersController(FactoryContext db)
        {
            _db = db;
        }
        public ActionResult Index()
        {
            List<Engineer> model = _db.Engineers.ToList();
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Engineer engineer)
        {
            _db.Engineers.Add(engineer);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Engineer thisEngineer = _db.Engineers
            .Include(engineer => engineer.JoinEntities)
            .ThenInclude(join => join.Machine)
            .FirstOrDefault(engineer => engineer.EngineerId == id);
            return View(thisEngineer);
        }

        public ActionResult Edit(int id)
        {
            Engineer thisEngineer = _db.Engineers
            .FirstOrDefault(engineer => engineer.EngineerId == id);
            return View(thisEngineer);
        }
        [HttpPost]
        public ActionResult Edit(Engineer engineer)
        {
            _db.Engineers.Update(engineer);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Engineer thisEngineer = _db.Engineers
            .FirstOrDefault(engineer => engineer.EngineerId == id);
            return View(thisEngineer);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Engineer thisEngineer = _db.Engineers
            .FirstOrDefault(engineer => engineer.EngineerId == id);
            _db.Engineers.Remove(thisEngineer);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
       public ActionResult AddMachine(int id)
        {
            Engineer thisEngineer = _db.Engineers
                            .FirstOrDefault(engineers => engineers.EngineerId == id);
            List<Machine> machines = _db.Machines.ToList();
            SelectList machineList = new SelectList(machines, "MachineId", "MachineName");
            ViewBag.MachineId = machineList;
            return View(thisEngineer);
        }

        [HttpPost]
        public ActionResult AddMachine(Engineer engineer, int machineId)
        {  
            #nullable enable
            EngineerMachine? joinEntity = _db.EngineerMachines
                                .FirstOrDefault(join => (join.MachineId == machineId && join.EngineerId == engineer.EngineerId));
            #nullable disable
            if (joinEntity == null && machineId != 0)
            {
                _db.EngineerMachines.Add(new EngineerMachine() { MachineId = machineId, EngineerId = engineer.EngineerId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = engineer.EngineerId });
        }
    }
}

Factory/Controllers/MachinesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }
        public ActionResult Index()
        {
            List<Machine> model = _db.Machines.ToList();
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Machine machine)
        {
            _db.Machines.Add(machine);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Machine thisMachine = _db.Machines
            .Include(machine => machine.JoinEntities)
            .ThenInclude(join => join.Engineer)
            .FirstOrDefault(machine => machine.MachineId == id);
            return View(thisMachine);
        }

        public ActionResult Edit(int id)
        {
            Machine thisMachine = _db.Machines
            .FirstOrDefault(machine => machine.MachineId == id);
            return View(thisMachine);
        }
        [HttpPost]
        public ActionResult Edit(Machine machine)
        {
            _db.Machines.Update(machine);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Machine thisMachine = _db.Machines
            .FirstOrDefault(machine => machine.MachineId == id);
            return View(thisMachine);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Machine thisMachine = _db.Machines
            .FirstOrDefault(machine => machine.MachineId == id);
            _db.Machines.Remove(thisMachine);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult AddEngineer(int id)
        {
            Machine thisMachine = _db.Machines
            .FirstOrDefault(machines => machines.MachineId == id);
            List<Engineer> engineers = _db.Engineers.ToList();
            SelectList engineerList = new SelectList(engineers,"EngineerId","EngineerName");
            ViewBag.EngineerId = engineerList;
            return View(thisMachine);
        }

          [HttpPost]
        public ActionResult AddEngineer(Machine machine, int engineerId)
        {
            #nullable enable
            EngineerMachine? joinEntity = _db.EngineerMachines
                                .FirstOrDefault(join => (join.EngineerId == engineerId && join.MachineId == machine.MachineId));
            #nullable disable
            if (joinEntity == null && engineerId != 0)
            {
                 _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = engineerId, MachineId = machine.MachineId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new {id = machine.MachineId});
        }
    }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
    Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Machine

<h2>Add this machine to an engineer @Html.DisplayFor(model => model.MachineName)</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MachineId)

    @Html.Label("Select an engineer")
    @Html.DropDownList("EngineerId")
    <input type="submit" value="save"/>

}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Add new engineer", "Create", "Engineers")</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<p>@Html.ValidationMessageFor(model => model.MachineName, "Name")</p>

<h4>Add new Machine</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.MachineName, "Name")
  @Html.TextBoxFor(model => model.MachineName)
  <br>

  <input type="submit" value="Add"  class="btn btn-primary"/>
}

<p> @Html.ActionLink("Back to List", "Index" )</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Do you want to delete this:</h2>

@Html.DisplayNameFor(model => model.MachineId)? 
@using (Html.BeginForm())

{
    <input type="submit" value="Delete" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine
@using Factory.Models

<h2>Details</h2>
<hr />

<h3>Machine: @Html.DisplayNameFor(model => model.MachineName)</h3>
<h3>Machine: @Html.DisplayFor(model => model.MachineName)</h3>

<h3>MACHINE: @Html.DisplayNameFor(model => model.MachineName)</h3>
<h3>MACHINE: @Html.DisplayFor(model => model.MachineName)</h3>


@if(@Model.JoinEntities.Count == 0)
{
  <p>This machine has not been assigned an engineer</p>
}
else
{

  <h4>Approved to work on with these engineers:</h4>

  <h4>Approved machines:</h4>

  List<EngineerMachine> machineList = new List<EngineerMachine>();
  <ul>
  @foreach(EngineerMachine join in Model.JoinEntities)
  {

    @join.Machine.EngineerName
    @using (Html.BeginForm("Engineers"))

    @join.Engineer.EngineerName
    @using (Html.BeginForm("Machines"))
    
    {
      @Html.Hidden("joinId", @join.EngineerMachineId)
      <input type="submit" value="Delete"class="btn btn-primary" />
    }
  }
  </ul>
}


<p>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId }) || @Html.ActionLink("Add to Engineer", "AddEngineer", new { id = Model.MachineId})</p>

<p>@Html.ActionLink("Remove this Machine", "Delete", new { id = Model.MachineId }) || @Html.ActionLink("Add new Engineer", "AddEngineer", "Machines")</p>

<p>@Html.ActionLink("Remove this machine", "Delete", new { id = Model.MachineId }) || @Html.ActionLink("Add new Engineer", "AddEngineer", "Machines")</p>

Factory/Views/Machines/Edit.cshtml
@{
    Layout = "_Layout";
}

@model Factory.Models.Machine

    <h1>Edit Machine</h1>
    <h3>Editing: @Html.DisplayFor(model => model.MachineName)</h3>

<hr />

@using (Html.BeginForm())
{
        @Html.HiddenFor(model => model.MachineId)
       
        <label class="label">@Html.DisplayNameFor(model => model.MachineName)</label>
        @Html.EditorFor(model => model.MachineName, new { @class = "form-control" })
        <p class="text-danger font-weight-bold">@Html.ValidationMessageFor(model => model.MachineName)</p>
      
    
        <label class="label">@Html.DisplayNameFor(model => model.ManufactureDate)</label>
        @Html.EditorFor(model => model.ManufactureDate, new { @class = "form-control", @type = "date" })
        <p class="text-danger font-weight-bold">@Html.ValidationMessageFor(model => model.ManufactureDate)</p>

        <button type="submit" class="btn btn-success">Save</button>


        <p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId }, new { @class = "btn btn-danger" })</p>
        <p>@Html.ActionLink("Back to All Machines", "Index", null, new { @class = "btn btn-secondary" })</p>

}

Factory/Views/Machines/Index.cshtml
@{
    Layout = "_Layout";
}

@using Factory.Models;

    <h1>Machines</h1>
<hr />

@if (Model.Count == 0)
{
    <p>No machines have been added yet.</p>
}
else
{
        @foreach (Machine machine in Model)
        {
            @machine.MachineName
            @machine.ManufactureDate
            @Html.ActionLink("Details", "Details", new { id = machine.MachineId })
        }
}

    @Html.ActionLink("Add New Machine", "Create", "Machines", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Return Home", "Index", "Home", null, new { @class = "btn btn-secondary" })