Factory/Models/Engineer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
    public class Engineer
    {
        public int EngineerId { get; set; }
        [Required(ErrorMessage = "Enter a name")]
        public string EngineerName { get; set; }
        public int MachineId { get; set; }
        
        public List<EngineerMachine> JoinEntities { get; }
    }
}

Factory/Controllers/EngineersController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
    public class EngineersController : Controller
    {
        private readonly FactoryContext _db;

        public EngineersController(FactoryContext db)
        {
            _db = db;
        }
        public ActionResult Index()
        {
            List<Engineer> model = _db.Engineers.ToList();
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Engineer engineer)
        {
            _db.Engineers.Add(engineer);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Engineer thisEngineer = _db.Engineers
            .Include(engineer => engineer.JoinEntities)
            .ThenInclude(join => join.Machine)
            .FirstOrDefault(engineer => engineer.EngineerId == id);
            return View(thisEngineer);
        }

        public ActionResult Edit(int id)
        {
            Engineer thisEngineer = _db.Engineers
            .FirstOrDefault(engineer => engineer.EngineerId == id);
            return View(thisEngineer);
        }
        [HttpPost]
        public ActionResult Edit(Engineer engineer)
        {
            _db.Engineers.Update(engineer);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Engineer thisEngineer = _db.Engineers
            .FirstOrDefault(engineer => engineer.EngineerId == id);
            return View(thisEngineer);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Engineer thisEngineer = _db.Engineers
            .FirstOrDefault(engineer => engineer.EngineerId == id);
            _db.Engineers.Remove(thisEngineer);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
       public ActionResult AddMachine(int id)
        {
            Engineer thisEngineer = _db.Engineers
                            .FirstOrDefault(engineers => engineers.EngineerId == id);
            List<Machine> machines = _db.Machines.ToList();
            SelectList machineList = new SelectList(machines, "MachineId", "MachineName");
            ViewBag.MachineId = machineList;
            return View(thisEngineer);
        }

        [HttpPost]
        public ActionResult AddMachine(Engineer engineer, int machineId)
        {  
            #nullable enable
            EngineerMachine? joinEntity = _db.EngineerMachines
                                .FirstOrDefault(join => (join.MachineId == machineId && join.EngineerId == engineer.EngineerId));
            #nullable disable
            if (joinEntity == null && machineId != 0)
            {
                _db.EngineerMachines.Add(new EngineerMachine() { MachineId = machineId, EngineerId = engineer.EngineerId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = engineer.EngineerId });
        }
    }
}

Factory/Controllers/MachinesController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }
        public ActionResult Index()
        {
            List<Machine> model = _db.Machines.ToList();
            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Machine machine)
        {
            _db.Machines.Add(machine);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Machine thisMachine = _db.Machines
            .Include(machine => machine.JoinEntities)
            .ThenInclude(join => join.Engineer)
            .FirstOrDefault(machine => machine.MachineId == id);
            return View(thisMachine);
        }

        public ActionResult Edit(int id)
        {
            Machine thisMachine = _db.Machines
            .FirstOrDefault(machine => machine.MachineId == id);
            return View(thisMachine);
        }
        [HttpPost]
        public ActionResult Edit(Machine machine)
        {
            _db.Machines.Update(machine);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Machine thisMachine = _db.Machines
            .FirstOrDefault(machine => machine.MachineId == id);
            return View(thisMachine);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Machine thisMachine = _db.Machines
            .FirstOrDefault(machine => machine.MachineId == id);
            _db.Machines.Remove(thisMachine);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult AddEngineer(int id)
        {
            Machine thisMachine = _db.Machines
            .FirstOrDefault(machines => machines.MachineId == id);
            List<Engineer> engineers = _db.Engineers.ToList();
            SelectList engineerList = new SelectList(engineers,"EngineerId","EngineerName");
            ViewBag.EngineerId = engineerList;
            return View(thisMachine);
        }

          [HttpPost]
        public ActionResult AddEngineer(Machine machine, int engineerId)
        {
            #nullable enable
            EngineerMachine? joinEntity = _db.EngineerMachines
                                .FirstOrDefault(join => (join.EngineerId == engineerId && join.MachineId == machine.MachineId));
            #nullable disable
            if (joinEntity == null && engineerId != 0)
            {
                 _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = engineerId, MachineId = machine.MachineId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new {id = machine.MachineId});
        }
    }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
    Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Engineer

<h2>Add this engineer to a machine @Html.DisplayFor(model => model.EngineerName)</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.EngineerId)

    @Html.Label("Select a machine")
    @Html.DropDownList("MachineId")
    <input type="submit" value="save"/>

}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Add new machine", "Create", "Machines")</p>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<p>@Html.ValidationMessageFor(model => model.EngineerName, "Name")</p>

<h4>Add new Engineer</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.EngineerName, "Name")
  @Html.TextBoxFor(model => model.EngineerName)
  <br>

  <input type="submit" value="Add"  class="btn btn-primary"/>
}

<p> @Html.ActionLink("Back to List", "Index" )</p>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Do you want to delete this:</h2>

@Html.DisplayNameFor(model => model.EngineerId)? 
@using (Html.BeginForm())

{
    <input type="submit" value="Delete" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer
@using Factory.Models

<h2>Details</h2>
<hr />
<h3>Employee: @Html.DisplayNameFor(model => model.EngineerName)</h3>
<h3>Employee: @Html.DisplayFor(model => model.EngineerName)</h3>


@if(@Model.JoinEntities.Count == 0)
{
  <p>This Engineer has not been assigned a machine</p>
}
else
{
  <h4>Approved to work on these Machines:</h4>
  List<EngineerMachine> machineList = new List<EngineerMachine>();
  <ul>
  @foreach(EngineerMachine join in Model.JoinEntities)
  {
    <li>@join.Machine.MachineName</li>
    @using (Html.BeginForm("Engineers"))
    {
      @Html.Hidden("joinId", @join.EngineerMachineId)
      <input type="submit" value="Delete"class="btn btn-primary" />
    }
  }
  </ul>
}

<div id="index-nav">
<p>@Html.ActionLink("Edit Engineer", "Edit", new { id = Model.EngineerId }) || @Html.ActionLink("Add to Machine", "AddMachine", new { id = Model.EngineerId})</p>
<p>@Html.ActionLink("Remove this Engineer", "Delete", new { id = Model.EngineerId }) || @Html.ActionLink("Add new Machine", "AddMachine", "Engineers")</p>
</div>

Factory/Views/Engineers/Edit.cshtml
@{
    Layout = "_Layout";
}

@model Factory.Models.Engineer


    <h1>Edit Engineer</h1>
    <h4>Editing: @Html.DisplayFor(model => model.EngineerName)</h4>

<hr />


    @using (Html.BeginForm())
    {
            @Html.HiddenFor(model => model.EngineerId)
                <label class="form-label">@Html.DisplayNameFor(model => model.EngineerName)</label>
                @Html.EditorFor(model => model.EngineerName, new { @class = "form-control" })
                <p class="text-danger">@Html.ValidationMessageFor(model => model.EngineerName)</p>
            <button type="submit" class="btn btn-success">Save</button>
    }

<hr />
        <p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId }, new { @class = "btn btn-danger" })</p>
        <p>@Html.ActionLink("Back to All Engineers", "Index", null, new { @class = "btn btn-secondary" })</p>

Factory/Views/Engineers/Index.cshtml
@{
    Layout = "_Layout";
}

@using Factory.Models;

    <h1>Engineers</h1>

<hr />

    @if (Model.Count == 0)
    {
        <p>No engineers have been added.</p>
    }
    else
    {
    
        @foreach (Engineer engineer in Model)
            {
                @engineer.EngineerName
                @Html.ActionLink("Details", "Details", new { id = engineer.EngineerId })
                 
            }
    }
<hr />

    @Html.ActionLink("Add New Engineer", "Create", "Engineers", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Return Home", "Index", "Home", null, new { @class = "btn btn-secondary" })